/**
 * Entity quality filter — rejects common English words, technical jargon,
 * and other non-name tokens that get misclassified as person/org entities.
 *
 * This module provides a single, comprehensive filter that should be used by
 * both person-service.ts and world-model.ts to prevent garbage entities from
 * entering the knowledge graph.
 *
 * Design goals:
 * - Generic: no hardcoded real names, works on any user's machine
 * - Comprehensive: covers common English vocabulary, tech jargon, business terms
 * - Conservative: single lowercase words that appear in a dictionary are rejected
 *   unless they pass additional name-quality heuristics
 */

// ---------------------------------------------------------------------------
// Common English words that are NOT person names
// ---------------------------------------------------------------------------
// This list covers: common verbs, adjectives, adverbs, nouns, technical terms,
// business jargon, programming concepts, and calendar/time words.
// All entries are lowercase. The filter normalizes input before checking.

const COMMON_ENGLISH_WORDS = new Set([
  // -- Articles, pronouns, prepositions, conjunctions, determiners --
  "about", "above", "across", "after", "again", "against", "all", "almost",
  "along", "already", "also", "always", "among", "and", "another", "any",
  "anybody", "anyone", "anything", "are", "around", "away",
  "back", "because", "been", "before", "being", "below", "between", "both",
  "but", "can", "cannot", "could", "cuz",
  "did", "didn", "does", "don", "done", "down", "during",
  "each", "either", "else", "enough", "even", "ever", "every",
  "few", "for", "from", "further",
  "get", "gets", "getting", "given", "got",
  "had", "has", "have", "having", "her", "here", "hers", "herself",
  "hey", "him", "himself", "his", "how", "however",
  "into", "its", "itself",
  "just",
  "keep", "keeps", "kept", "know", "known",
  "last", "let", "like", "long", "looking",
  "made", "make", "makes", "making", "many", "may", "maybe", "might",
  "more", "most", "much", "must",
  "need", "needed", "needs", "never", "new", "next", "nobody", "none",
  "nor", "not", "nothing", "now",
  "off", "often", "okay", "old", "once", "one", "only", "onto", "open",
  "other", "our", "out", "over", "own",
  "part", "past", "per", "please", "put",
  "quite",
  "rather", "really",
  "said", "same", "say", "says", "see", "seen", "set", "shall", "she",
  "should", "show", "shows", "since", "small", "some", "something",
  "sometimes", "soon", "still", "such",
  "take", "than", "that", "the", "their", "them", "then", "there",
  "these", "they", "thing", "things", "think", "this", "those", "though",
  "three", "through", "till", "too", "toward", "towards", "try", "two",
  "under", "until", "upon", "use", "used", "uses", "using",
  "very",
  "want", "wants", "was", "way", "well", "were", "what", "when",
  "where", "whether", "which", "while", "who", "whom", "whose", "why",
  "will", "with", "within", "without", "would",
  "yeah", "yes", "yet", "you", "your",

  // -- Common verbs (present, past, gerund forms) --
  "accept", "accepted", "achieve", "achieved", "act", "action", "actions",
  "activate", "adapted", "add", "added", "adjust", "adjusted", "apply",
  "applied", "applicable", "approve", "approved", "approvals",
  "ask", "asked", "assess", "assessment", "assign", "assigned", "assume",
  "attempted",
  "block", "blocked", "blocker", "blockers", "bought", "break", "bring",
  "browse", "browsed", "build", "built", "buy", "buying",
  "call", "called", "came", "capture", "captured", "carry", "catch",
  "cause", "caused", "change", "changed", "changes", "check", "checked",
  "checks", "choose", "claim", "claimed", "clean", "cleaned", "cleanup",
  "clear", "cleared", "close", "closed", "collect", "come", "coming",
  "commit", "commits", "compare", "complete", "completed", "compose",
  "compute", "conclude", "condition", "conduct", "configure", "confirm",
  "confirmed", "confirmation", "connect", "consider", "consume", "contain",
  "continue", "control", "convert", "copy", "correct", "count", "cover",
  "cowork", "create", "created", "cut",
  "decide", "declare", "define", "deliver", "delivery", "deployed", "describe",
  "design", "detect", "determine", "develop", "disable", "disabled",
  "discover", "discovery", "discuss", "display", "distribute", "divide",
  "drop",
  "earn", "edit", "embed", "embedded", "enable", "enabled", "ensure",
  "enter", "estimate", "evaluate", "examine", "example", "examples",
  "exchange", "execute", "execution", "exercise", "existing", "expand",
  "expect", "experience", "explain", "explicit", "export", "expose",
  "extend", "extract", "extraction",
  "face", "fail", "failed", "fall", "feature", "features", "feed", "feel",
  "fetch", "figure", "fill", "filter", "find", "finish", "fix", "fixed",
  "fly", "focus", "follow", "force", "forget", "form", "format", "found",
  "fulfill",
  "gain", "gather", "gathered", "generate", "generating", "generation",
  "give", "going", "grant", "grants", "grow", "guess",
  "hand", "handle", "handler", "happen", "harness", "head", "hear",
  "help", "hide", "hit", "hold", "holding", "hope",
  "ignore", "imagine", "implement", "implementation", "import", "improve",
  "improvement", "include", "increase", "indicate", "inform", "input",
  "insert", "install", "integrate",
  "join", "jump",
  "kill", "killer",
  "launch", "lead", "learn", "learning", "leave", "lend", "limit", "link",
  "links", "list", "listen", "live", "load", "lock", "locked", "log",
  "logged", "logging", "logs", "look", "lose", "loss",
  "maintain", "manage", "map", "mark", "match", "matter", "mean",
  "measure", "meet", "meeting", "mention", "merge", "mind", "miss",
  "missing", "mix", "modify", "modified", "monitor", "move", "multiple",
  "note", "noted", "notes", "notice",
  "observe", "observation", "obtain", "occur", "offer", "offers",
  "operate", "operating", "operations", "operator", "option", "optional",
  "order", "orient", "organize", "output", "outputs", "overcome", "overlap",
  "overnight", "override", "own", "owner",
  "package", "page", "paid", "parse", "pass", "passed", "pattern",
  "patterns", "pause", "pay", "peak", "pending", "perform", "performance",
  "permit", "pick", "pitch", "place", "plan", "play", "point", "poll",
  "position", "post", "power", "practice", "predict", "prefer", "prep",
  "prepare", "present", "press", "prevent", "previously", "price",
  "pricing", "primary", "prior", "priority", "probe", "process",
  "processes", "produce", "product", "production", "program", "progress",
  "projects", "promise", "promote", "proof", "protect", "protection",
  "prove", "provide", "pull", "push", "put",
  "query", "queries", "question", "queue", "quotes", "quit",
  "raise", "ran", "range", "rank", "rate", "reach", "read", "ready",
  "readiness", "real", "realize", "receive", "recognize", "recommend",
  "recommendation", "recommended", "reconfirmed", "record", "records",
  "recurrence", "reduce", "refer", "reflect", "register", "reject",
  "relate", "related", "release", "remain", "remaining", "remember",
  "remove", "render", "repeat", "replace", "report", "reports", "request",
  "requested", "require", "resend", "resolve", "resolved", "resolving",
  "respond", "response", "responses", "rest", "restore", "result",
  "results", "retain", "retainers", "retrieval", "return", "reveal",
  "review", "reviewed", "revised", "rewrite", "risk", "roll", "rollover",
  "run", "running",
  "safe", "save", "say", "scale", "scan", "schedule", "scope", "search",
  "secure", "seek", "seem", "segment", "select", "sell", "send", "sender",
  "separate", "sequence", "sequential", "serve", "service", "services",
  "settle", "shape", "share", "shift", "ship", "show", "shut", "sign",
  "signal", "simple", "simplify", "sit", "size", "skip", "sleep", "slide",
  "slow", "solve", "sort", "source", "spawn", "speak", "specialized",
  "specific", "specify", "speed", "spend", "split", "spread", "sprint",
  "stand", "standing", "start", "started", "state", "stay", "step",
  "steps", "stick", "stop", "store", "stored", "stores", "strengthen",
  "strength", "stretch", "strike", "structure", "study", "submit",
  "succeed", "success", "suggest", "suggested", "summarize", "supply",
  "support", "suppose", "sure", "surface", "switch", "sync",
  "synthesized",
  "tag", "tags", "talk", "target", "teach", "tell", "tend", "test",
  "tests", "text", "throw", "tie", "tightened", "tip", "title", "top",
  "total", "touch", "track", "trade", "train", "training", "transcript",
  "transfer", "transform", "translate", "treat", "trigger", "trim",
  "trust", "truth", "try", "turn", "type",
  "understand", "unified", "unite", "unknown", "unlock", "update",
  "updated", "updates", "upgrade", "upload", "usage", "uses",
  "validate", "value", "values", "vary", "verify", "verified", "version",
  "view", "visible", "visit", "voice", "vote",
  "wait", "waiting", "walk", "warn", "warning", "watch", "weather",
  "weigh", "welcome", "why", "win", "wire", "wish", "withdraw",
  "wonder", "work", "works", "working", "workbook", "workflows",
  "workgraph", "write", "writer",
  "yield",
  "zero", "zone",

  // -- Common adjectives / adverbs --
  "able", "above", "absent", "absolute", "abstract", "acceptable",
  "accessible", "accurate", "active", "actual", "actually", "adequate",
  "advanced", "afraid", "aggressive", "alike", "alive", "alone",
  "alternative", "amazing", "angry", "annual", "apparent", "appropriate",
  "approximate", "arbitrary", "attractive", "authenticated", "automatic",
  "autonomous", "available", "average", "awesome",
  "bad", "bare", "base", "basic", "beautiful", "best", "better", "big",
  "blank", "blind", "brave", "brief", "bright", "broad", "broken",
  "busy",
  "calm", "canonical", "capable", "capability", "careful", "casual",
  "central", "certain", "cheap", "chief", "civil", "classic", "clean",
  "clear", "clever", "cold", "comfortable", "common", "compact",
  "compatible", "competitive", "complete", "complex", "complexity",
  "compliant", "compliance", "compound", "comprehensive", "concerned",
  "concrete", "confident", "conscious", "consistent", "constant",
  "contemporary", "content", "continuous", "convenient", "conventional",
  "cool", "corporate", "correct", "cost", "creative", "critical",
  "crucial", "curious", "current", "currently", "custom",
  "daily", "dangerous", "dark", "dead", "dear", "decent", "deep",
  "definite", "deliberate", "delicate", "dependent", "desperate",
  "detailed", "different", "difficult", "digital", "direct", "dirty",
  "distinct", "diverse", "double", "dramatic", "dry", "dull", "dynamic",
  "eager", "early", "easily", "eastern", "easy", "economic", "effective",
  "efficient", "electronic", "elegant", "elementary", "eligible",
  "emotional", "empty", "enormous", "entire", "environmental", "equal",
  "equivalent", "essential", "even", "eventual", "every", "evident",
  "exact", "excellent", "excessive", "exciting", "exclusive", "executive",
  "existing", "expensive", "experienced", "expert", "explicit", "express",
  "extensive", "external", "extra", "extraordinary", "extreme",
  "fair", "false", "familiar", "famous", "fancy", "fantastic", "far",
  "fast", "fat", "favorable", "federal", "final", "financial", "fine",
  "firm", "fit", "flat", "flexible", "flying", "formal", "former",
  "forward", "free", "frequent", "frequency", "fresh", "friendly",
  "front", "frozen", "full", "fun", "functional", "fundamental", "funny",
  "future",
  "general", "generally", "generous", "gentle", "genuine", "giant",
  "glad", "global", "golden", "good", "gorgeous", "gradual", "grand",
  "grateful", "grave", "gray", "grayed", "great", "green", "gross",
  "guilty",
  "half", "handy", "happy", "hard", "harsh", "healthy", "heavy", "helpful",
  "hidden", "high", "historic", "holy", "honest", "horrible", "hostile",
  "hot", "hourly", "huge", "human", "hungry", "hybrid",
  "ideal", "idle", "illegal", "immediate", "immense", "important",
  "impossible", "impressive", "inactive", "incredible", "independent",
  "individual", "industrial", "inevitable", "infinite", "informal",
  "initial", "inner", "innocent", "innovative", "instant", "intelligent",
  "intense", "interesting", "interim", "internal", "invalid",
  "invisible", "involved",
  "joint", "junior",
  "keen", "key", "kind",
  "large", "late", "latest", "leading", "lean", "legal", "legitimate",
  "level", "liberal", "light", "likely", "limited", "linear", "little",
  "living", "local", "logical", "lonely", "loose", "lossless", "lost",
  "loud", "low", "lucky",
  "mad", "magic", "main", "major", "manual", "many", "marginal", "massive",
  "material", "mature", "maximum", "mean", "medical", "medium", "mental",
  "mere", "mid", "middle", "mild", "military", "minimum", "minor",
  "minute", "mobile", "moderate", "modern", "modest", "monthly",
  "moral", "multiple", "mutual",
  "narrow", "nasty", "native", "natural", "near", "neat", "necessary",
  "negative", "nervous", "neutral", "nice", "niche", "nightly", "noble",
  "nominal", "normal", "northern", "notable", "novel", "numerous",
  "objective", "obvious", "obviously", "occasional", "odd", "official",
  "okay", "only", "open", "operational", "opposite", "optimal",
  "ordinary", "organic", "original", "overall", "overseas",
  "pale", "parallel", "partial", "particular", "passive", "patient",
  "perfect", "permanent", "personal", "physical", "plain", "pleasant",
  "plenty", "plus", "polite", "political", "poor", "popular", "portable",
  "positive", "possible", "potential", "powerful", "practical", "precise",
  "premium", "prepared", "previous", "prime", "primitive", "principal",
  "probable", "productive", "professional", "profound", "progressive",
  "prominent", "proper", "prospective", "protective", "proud",
  "provisional", "public", "pure",
  "quick", "quiet",
  "radical", "random", "rapid", "rare", "raw", "reactive", "real",
  "realistic", "reasonable", "recent", "recreational", "red", "redundant",
  "regular", "relevant", "reliable", "reluctant", "remarkable", "remote",
  "repeated", "representative", "reproducible", "residential",
  "resistant", "respective", "responsible", "rich", "rigid", "rough",
  "round", "routine", "rural",
  "sacred", "sad", "safe", "secure", "selective", "senior",
  "sensitive", "separate", "serious", "severe", "shallow", "sharp",
  "sheer", "short", "sick", "significant", "silent", "silly", "similar",
  "simple", "single", "slight", "slim", "slow", "smooth", "so",
  "social", "soft", "solid", "sophisticated", "sorry", "sound",
  "southern", "spare", "spatial", "special", "specific", "spectacular",
  "stable", "stale", "standard", "static", "steady", "steep",
  "still", "straight", "strange", "strategic", "strategy", "strict",
  "strong", "structural", "subtle", "sudden", "sufficient", "suitable",
  "super", "superior", "sure", "surplus", "surprising", "sustainable",
  "sweet", "swift", "systematic",
  "tactical", "tactics", "tall", "temporary", "tender", "terminal",
  "terrible", "thick", "thin", "thorough", "tight", "tiny", "tired",
  "top", "total", "tough", "traditional", "transient", "transparent",
  "tremendous", "trim", "triple", "trivial", "true", "typical",
  "ugly", "ultimate", "unable", "uncertain", "unchanged", "uncommon",
  "underground", "underlying", "unfair", "uniform", "unique",
  "universal", "unlikely", "unnecessary", "unusual", "upfront",
  "upper", "upset", "urban", "urgent", "useful", "usual",
  "vacant", "vague", "valid", "valuable", "variable", "various",
  "verbal", "vertical", "viable", "violent", "virtual", "visible",
  "visual", "vital", "vivid", "voluntary", "vulnerable",
  "warm", "weak", "weekly", "weird", "western", "wet", "white",
  "whole", "wide", "wild", "willing", "wise", "wonderful", "wooden",
  "worthy", "wrong",
  "young",

  // -- Common nouns --
  "academy", "access", "account", "accuracy", "action", "activity",
  "address", "admin", "advantage", "advice", "affair", "agency",
  "agenda", "agent", "agents", "agreement", "aid", "aim", "air",
  "alert", "algorithm", "analysis", "analyst", "analytics", "anchor",
  "angle", "announcement", "answer", "app", "appeal", "appearance",
  "approach", "approval", "approvals", "architect", "architecture",
  "area", "argument", "army", "arrangement", "array", "art", "article",
  "aspect", "assembly", "asset", "assignment", "assistance", "assistants",
  "association", "assumption", "atmosphere", "attempt", "attention",
  "attitude", "audience", "audit", "authority", "authorization",
  "auto", "automation", "awareness",
  "backend", "background", "backlog", "backup", "badge", "balance",
  "band", "bank", "barrier", "base", "baseline", "basis", "batch",
  "bearer", "beauty", "beginning", "behavior", "belief", "bell",
  "benchmark", "benchmarks", "benefit", "bill", "bit", "blade",
  "blame", "blend", "blog", "blow", "board", "body", "bond", "bonus",
  "book", "border", "boss", "bottleneck", "bottom", "boundary",
  "boundaries", "box", "brain", "branch", "brand", "breach", "bridge",
  "browser", "bucket", "budget", "buff", "buffer", "bug", "builder",
  "burden", "bus", "button", "buyer",
  "cabin", "cable", "cache", "calendar", "campaign", "candidate",
  "capacity", "capital", "card", "career", "carrier", "case", "cash",
  "cast", "catalog", "category", "cause", "cell", "center", "chain",
  "chair", "challenge", "champion", "chance", "channel", "chapter",
  "character", "charge", "charity", "chart", "chat", "chip", "choice",
  "chunk", "circle", "circuit", "citizen", "claim", "class", "classic",
  "client", "clinic", "clip", "clock", "cloud", "cluster", "coach",
  "coaching", "coalition", "code", "coding", "coin", "collapse",
  "colleague", "collection", "column", "combination", "comfort",
  "command", "commands", "commerce", "commission", "commitment",
  "committee", "community", "companion", "comparison", "compensation",
  "competition", "competitors", "complaint", "component", "composition",
  "concept", "concern", "conclusion", "concrete", "condition",
  "conference", "confidence", "conflict", "confusion", "connection",
  "consciousness", "consensus", "consequence", "consideration",
  "conspiracy", "constraint", "constraints", "construction",
  "consultant", "consulting", "consumer", "consumption", "contact",
  "container", "content", "contest", "context", "contract", "contrast",
  "contribution", "control", "controversy", "convention", "conversation",
  "conversion", "conviction", "cooperation", "coordination", "copy",
  "core", "corner", "correction", "correlation", "correspondence",
  "corridor", "cost", "count", "counter", "country", "county",
  "couple", "courage", "course", "court", "cover", "crash", "creation",
  "creature", "credit", "crew", "crime", "crisis", "criteria",
  "criticism", "crop", "crowd", "culture", "cup", "currency", "curve",
  "customer", "cut", "cycle",
  "damage", "danger", "dashboard", "data", "database", "date",
  "daughter", "dawn", "day", "days", "deal", "death", "debate", "debt",
  "decade", "decision", "deck", "decline", "default", "defence",
  "deficit", "degree", "delay", "delegate", "deliverable", "delivery",
  "demand", "democracy", "demonstration", "department", "departure",
  "depth", "deputy", "description", "desert", "designer",
  "desire", "desk", "destination", "detail", "details", "detector",
  "determination", "dev", "developer", "development", "device",
  "diagnostic", "dialogue", "diet", "difference", "difficulty",
  "dimension", "direction", "director", "directory", "discipline",
  "discount", "discourse", "discovery", "discussion", "disease",
  "disorder", "dispute", "distance", "distinction", "distribution",
  "district", "diversity", "division", "doc", "docs", "document",
  "documentation", "dollar", "domain", "door", "dose", "doubt",
  "draft", "drama", "draw", "dream", "dress", "drift", "drink",
  "driver", "drop", "drug", "duration", "dust", "duty",
  "earth", "ease", "economy", "ecosystem", "edge", "edition",
  "education", "effect", "efficiency", "effort", "ego", "element",
  "elevation", "emergency", "emission", "emotion", "emphasis",
  "empire", "employer", "employment", "encounter", "encouragement",
  "end", "enemy", "energy", "enforcement", "engagement", "engine",
  "engineering", "enterprise", "entertainment", "enthusiasm", "entity",
  "entries", "entry", "env", "environment", "episode", "episodic",
  "equality", "equipment", "era", "error", "errors", "escape", "essay",
  "essence", "establishment", "estate", "evaluation", "event",
  "evidence", "evolution", "examination", "exception", "exchange",
  "excitement", "excuse", "exercise", "exhibition", "existence",
  "expansion", "expectation", "expedition", "expenditure", "expense",
  "experiment", "explanation", "explosion", "exposure", "expression",
  "extension", "extent", "eye",
  "fabric", "facility", "fact", "factor", "factory", "faculty",
  "failure", "faith", "fallback", "fame", "family", "fan", "fantasy",
  "fare", "farm", "farmer", "fashion", "fate", "fault", "fear",
  "feast", "feature", "fee", "feed", "feedback", "feeling", "fellow",
  "fence", "festival", "fiction", "field", "fight", "file", "files",
  "film", "finger", "fire", "flag", "flame", "fleet", "flesh",
  "flexibility", "flight", "flood", "floor", "flow", "focus",
  "folder", "folk", "food", "fool", "foot", "football", "force",
  "forecast", "forest", "forever", "formula", "fortune", "forum",
  "forward", "fossil", "foundation", "founder", "fraction", "frame",
  "framework", "frameworks", "franchise", "fraud", "freedom",
  "frequency", "front", "frontier", "frost", "fruit", "fuel",
  "function", "fund", "fundamental", "funding", "funnel", "furniture",
  "fury", "future",
  "gain", "gallery", "game", "gamma", "gap", "garden", "gas", "gate",
  "gear", "gender", "gene", "genius", "genre", "gesture", "gift",
  "gist", "glass", "glimpse", "glory", "glue", "goal", "gold",
  "goods", "governance", "government", "governor", "grace", "grade",
  "gradient", "grain", "grammar", "graph", "grass", "grave",
  "gravity", "grip", "grocery", "ground", "group", "growth", "guard",
  "guidance", "guide", "guilt", "gun",
  "habit", "hall", "halt", "hardware", "harm", "harmony", "harvest",
  "hatred", "hazard", "headline", "headquarters", "health",
  "heartbeat", "heat", "height", "heritage", "hero", "hierarchy",
  "highlight", "hint", "history", "hobby", "hole", "holiday", "home",
  "honor", "hook", "hooks", "horizon", "horror", "horse", "hospital",
  "host", "hotel", "household", "housing", "hub",
  "icon", "idea", "identity", "ideology", "illness", "illusion",
  "illustration", "image", "imagination", "impact", "impulse",
  "inbox", "incentive", "incident", "income", "independence",
  "index", "indication", "indicator", "industry", "inequality",
  "infection", "inflation", "influence", "info", "information",
  "infrastructure", "ingredient", "inheritance", "initiative",
  "injury", "innovation", "input", "inquiry", "insight",
  "inspection", "inspiration", "instance", "institution", "instrument",
  "insurance", "intake", "integration", "integrity", "intellect",
  "intelligence", "intention", "interaction", "interest", "interface",
  "interference", "interior", "interpretation", "intervention",
  "introduction", "invasion", "invention", "investigation",
  "investment", "investor", "invitation", "involvement",
  "isolation", "issue", "issues", "item", "items",
  "jail", "jam", "jaw", "jet", "jewel", "job", "jobs", "joint",
  "joke", "journal", "journalism", "journey", "joy", "judgment",
  "juice", "jump", "jungle", "jurisdiction", "jury", "justice",
  "key", "kid", "kingdom", "kit", "kitchen", "knee", "knife",
  "knowledge",
  "label", "labor", "laboratory", "lack", "lady", "lake", "land",
  "landscape", "language", "laptop", "launch", "law", "lawn", "layer",
  "layout", "leadership", "league", "lecture", "ledger", "legacy",
  "legend", "legends", "legislation", "leisure", "lesson", "letter",
  "leverage", "liability", "liberty", "library", "licence", "lid",
  "lie", "lifecycle", "lifestyle", "lifetime", "lift", "light",
  "likelihood", "limit", "limitation", "line", "lines", "link",
  "lion", "lip", "list", "listener", "literacy", "literature",
  "living", "load", "loan", "lobby", "location", "logic", "loop",
  "loss", "lot", "luck", "lunch", "lung",
  "machine", "magazine", "magic", "mail", "mainstream", "maintenance",
  "majority", "maker", "mandate", "manner", "manuscript", "map",
  "march", "margin", "mark", "market", "marketplace", "mask",
  "mass", "master", "match", "material", "math", "matrix", "matter",
  "maximum", "meal", "meaning", "means", "measurement", "meat",
  "mechanism", "media", "medicine", "medium", "member", "membership",
  "memo", "memoir", "memorial", "memory", "mention", "mentor",
  "merchandise", "mercy", "merit", "mess", "message", "messages",
  "meta", "metadata", "metal", "method", "metric", "metrics",
  "migration", "milestone", "mill", "mind", "mine", "mineral",
  "minimum", "minister", "ministry", "minority", "miracle", "mirror",
  "misconception", "mission", "mistake", "mix", "mixture", "mob",
  "mode", "model", "models", "module", "moment", "momentum", "money",
  "monitor", "month", "mood", "moon", "morning", "mortgage",
  "mother", "motion", "motivation", "motivational", "motor", "mount",
  "mountain", "mouth", "movement", "movie", "mud", "muscle", "museum",
  "music", "mystery",
  "nail", "name", "narrative", "nation", "nature", "navigation",
  "necessity", "neck", "needle", "negotiation", "nerve",
  "nest", "net", "network", "news", "newspaper", "night",
  "nightmare", "noise", "nomination", "norm", "nose", "notion",
  "nucleus", "nudge", "number", "nurse", "nut", "nutrition",
  "objection", "obligation", "obstacle", "occasion", "occupation",
  "occurrence", "odds", "offense", "office", "officer",
  "offspring", "oil", "operation", "opinion", "opponent",
  "opportunity", "opposition", "optimism", "orbit", "orchestra",
  "organization", "orientation", "origin", "outcome", "outline",
  "outlook", "output", "outrage",
  "pace", "pack", "pair", "palace", "palm", "pan", "panel",
  "panic", "paper", "parade", "paragraph", "parent", "park",
  "parliament", "partner", "partnership", "party", "passage",
  "passion", "passport", "path", "paths", "patience", "patrol",
  "pause", "payment", "peace", "peak", "penalty", "pension",
  "perception", "period", "permission", "permit", "persistence",
  "personality", "perspective", "petition", "phase", "phenomenon",
  "philosophy", "phone", "photo", "photograph", "phrase", "piece",
  "pile", "pilot", "pin", "pipe", "pipeline", "pit", "place",
  "planet", "planner", "plant", "plate", "platform", "play",
  "player", "playbook", "plea", "pleasure", "pledge", "plot",
  "plug", "pocket", "poem", "poet", "poetry", "pole", "police",
  "policy", "politics", "pollution", "pool", "pop", "popularity",
  "population", "port", "portion", "portrait", "pose",
  "possession", "possibility", "pot", "poverty", "powder",
  "praise", "prayer", "precedent", "prediction",
  "prefix", "prefetch", "prejudice", "premise", "preparation",
  "presence", "presentation", "preservation", "presidency",
  "press", "pressure", "prestige", "prevention", "pride",
  "priest", "principle", "print", "prison", "prisoner", "privacy",
  "privilege", "prize", "procedure", "proceeding", "processor",
  "profession", "professor", "profile", "profit", "profound",
  "progression", "prohibition", "project", "projection",
  "prominence", "promotion", "prompt", "propaganda", "property",
  "proportion", "proposal", "proposition", "prosecution",
  "prospect", "prosperity", "protection", "protein", "protest",
  "protocol", "provision", "provocation", "pub", "publication",
  "publicity", "publisher", "punishment", "pupil", "purchase",
  "pursuit", "puzzle",
  "qualification", "quarter", "queen", "quest", "question",
  "quota",
  "race", "racism", "radar", "radiation", "rage", "rail", "rain",
  "rally", "ranch", "ratio", "reaction", "reader", "realm",
  "reason", "rebel", "rebellion", "receipt", "reception",
  "recession", "recipe", "recognition", "reconciliation",
  "reconstruction", "recovery", "recruitment", "reduction",
  "referendum", "reflection", "reform", "refuge", "refugee",
  "regime", "region", "regulation", "rehabilitation", "reign",
  "rejection", "relation", "relaxation", "relay", "relevance",
  "relief", "religion", "reluctance", "remedy", "reminder",
  "renewal", "rent", "repair", "repetition", "replacement",
  "replica", "representation", "reproduction", "republic",
  "reputation", "rescue", "resemblance", "reservation",
  "residence", "resignation", "resistance", "resolution",
  "resort", "resource", "respect", "restoration", "restriction",
  "retirement", "retreat", "revelation", "revenge", "revenue",
  "reverse", "revolution", "reward", "rhythm", "ride", "rifle",
  "ring", "riot", "rise", "ritual", "rival", "road", "rock",
  "role", "roof", "root", "rope", "rotation", "route", "router",
  "routine", "row", "royalty", "ruin", "rule", "rumor",
  "sacrifice", "sadness", "safety", "saint", "salary", "sale",
  "sales", "salt", "salvation", "sample", "sand", "satellite",
  "satisfaction", "sauce", "saving", "scandal", "scarcity",
  "scenario", "scene", "scheme", "scholar", "scholarship",
  "school", "science", "scientist", "scope", "score", "screen",
  "script", "sculpture", "sea", "seal", "season", "seat",
  "secret", "secretary", "sector", "security", "seed",
  "selection", "sensation", "sense", "sensitivity",
  "sentence", "sentiment", "sequel", "series", "sermon",
  "session", "setup", "settlement", "shade", "shadow", "shape",
  "shelf", "shell", "shelter", "shield", "shift", "ship",
  "shock", "shop", "shore", "shortage", "shot", "shoulder",
  "shout", "side", "siege", "sight", "signature", "significance",
  "silence", "silk", "silver", "simplicity", "simulation",
  "sin", "singer", "site", "situation", "skeleton", "skeptics",
  "sketch", "skill", "skin", "skull", "sky", "slap", "slave",
  "sleeve", "slice", "slot", "slots", "smoke", "snap", "snow",
  "snowball", "soap", "socket", "soil", "soldier", "solidarity",
  "solution", "song", "soul", "sound", "soup",
  "sovereignty", "space", "span", "spark", "specialist",
  "specification", "specimen", "spectacle", "spectrum",
  "speculation", "speech", "sphere", "spike", "spin", "spirit",
  "spot", "spouse", "squad", "stability", "stack", "stadium",
  "staff", "stage", "stake", "stall", "stamp", "stance",
  "standard", "standpoint", "standup", "star", "starter",
  "statement", "station", "statistics", "statue", "statute",
  "stem", "stereotype", "stick", "stimulus", "stock", "stomach",
  "stone", "storage", "store", "storm", "story", "strain",
  "strand", "stranger", "strap", "stream", "street", "stress",
  "stride", "string", "strip", "stroke", "struggle",
  "structure", "stuff", "style", "subagent", "subject",
  "submission", "substance", "substitute", "suburb",
  "succession", "suffering", "suggestion", "suit", "suite",
  "sum", "summary", "summit", "sunrise", "sunset",
  "supervision", "supplement", "supporter", "suppression",
  "surface", "surgeon", "surplus", "surprise", "surrender",
  "surroundings", "surveillance", "survival", "survivor",
  "suspect", "suspension", "suspicion", "swap", "sweep",
  "swing", "sword", "symbol", "sympathy", "syndrome",
  "syntax", "system",
  "table", "tablet", "tactic", "tail", "tale", "talent", "tank",
  "tape", "tea", "teacher", "team", "tear", "technique",
  "technology", "telephone", "telescope", "television",
  "temperature", "temple", "tendency", "tension", "tent", "tenure",
  "terms", "terrain", "territory", "terror", "testimony",
  "texture", "theme", "therapy", "thesis", "thought",
  "threat", "threshold", "throne", "thumb", "ticket",
  "tide", "tier", "tiered", "tiger", "timber", "timeline",
  "timer", "timing", "tissue", "toll", "tone",
  "tongue", "tool", "tools", "torch", "tour", "tournament",
  "tower", "town", "trace", "track", "tradition", "traffic",
  "tragedy", "trail", "trait", "transformation", "transit",
  "transition", "transmission", "transport", "trap", "trauma",
  "travel", "treasure", "treaty", "tree", "trend", "trial",
  "tribe", "tribute", "trick", "triumph", "troop", "trophy",
  "trouble", "truck", "trunk", "tube", "tumor",
  "tune", "tunnel", "turf", "turnover", "twin",
  "umbrella", "uncertainty", "uncle", "understanding", "union",
  "unity", "universe", "university", "upgrade", "upset",
  "urge", "urgency", "utility",
  "vacation", "valley", "van", "vanity", "variation", "variety",
  "vault", "vector", "vectors", "vehicle", "vendor", "venture",
  "venue", "verdict", "verse", "vessel", "veteran", "victim",
  "victory", "video", "videos", "viewer", "village", "villain",
  "violation", "violence", "virtue", "vision", "visitor",
  "vocabulary", "volcano", "volume", "volunteer", "vulnerability",
  "wage", "wall", "wallet", "war", "ward", "warehouse",
  "warfare", "warrior", "waste", "wave", "way", "weakness",
  "wealth", "weapon", "web", "webinar", "website",
  "wedding", "week", "weight", "welfare", "west", "wheel",
  "whistle", "width", "wife", "wilderness", "wind", "window",
  "wing", "winter", "wisdom", "witch", "witness", "wolf",
  "woman", "wonder", "wood", "wool", "word", "worker",
  "workplace", "workshop", "world", "worship", "wound", "wrap",
  "wrath", "wreck",
  "yard", "year", "youth",
  "zeal",

  // -- Tech/programming/ops terms --
  "api", "app", "apps", "async", "atomizer", "auth", "backend",
  "backup", "binary", "bitmap", "blob", "boolean", "boot", "buffer",
  "cache", "callback", "cdn", "cipher", "class", "cli", "cloud",
  "cloudflare", "cluster", "codex", "coe", "compile", "compiler",
  "config", "configs", "constructor", "container", "cors", "cron",
  "crons", "crud", "css", "cursor", "daemon", "debug", "debugger",
  "decode", "decrypt", "dependency", "deploy", "deployment",
  "deprecated", "destructor", "dev", "devops", "diff", "digest",
  "disk", "dns", "docker", "driver", "dump",
  "email", "encode", "encrypt", "endpoint", "env",
  "epoch", "eval", "event", "exception", "exec", "executor",
  "export",
  "fetch", "fiber", "firewall", "firmware", "flag", "float",
  "frontend", "fullstack", "function",
  "garbage", "gateway", "git", "glob", "gpu", "grep", "gui",
  "handler", "hash", "hashmeta", "heap", "hook", "hostname", "html",
  "http", "https",
  "ide", "import", "index", "init", "inject", "instance", "int",
  "integer",
  "java", "javascript", "json", "jwt",
  "kernel", "key", "keyword",
  "lambda", "latency", "lib", "library", "lint", "linux",
  "listener", "localhost", "lock", "logger",
  "macro", "malloc", "markup", "marshal", "merge", "method",
  "middleware", "minion", "mock", "module", "mutex",
  "namespace", "nearshore", "net", "nginx", "node", "nonce",
  "npm", "null",
  "oauth", "object", "offset", "opcode", "openai", "openclaw",
  "operand", "orm",
  "packet", "padding", "parameter", "parser", "patch", "payload",
  "persist", "pixel", "plugin", "plugins", "pointer", "polyfill",
  "port", "postgres", "prefix", "process", "prod", "profiler",
  "promise", "prompt", "property", "proxy", "pull", "push",
  "python",
  "queue", "query",
  "race", "rack", "railway", "ram", "random", "react", "readonly",
  "realtime", "rebase", "redis", "redirect", "refactor", "regex",
  "relay", "release", "render", "replica", "repo", "repl",
  "request", "resolver", "rest", "retry", "rollback", "rollout",
  "runtime", "rust",
  "sandbox", "scalar", "schema", "sdk", "seed", "selector",
  "semaphore", "server", "serverless", "servlet", "sha", "shell",
  "shim", "signal", "singleton", "slack", "slackbot", "snippet",
  "socket", "software", "sql", "ssh", "ssl", "stack", "staging",
  "stderr", "stdin", "stdout", "storage", "string", "struct",
  "subagent", "subreddit", "substack", "subnet", "supervisor",
  "swagger", "switch", "symlink", "syscall",
  "tailscale", "tcp", "telegram", "template", "tenant", "terminal",
  "terraform", "test", "testing", "thread", "throughput", "timeout",
  "timestamp", "tls", "token", "toolchain", "toolkit", "topology",
  "trace", "tracker", "trait", "transpile", "trigger", "truncate",
  "tuple", "twitter", "typedef", "typescript",
  "udp", "uid", "unix", "uptime", "uri", "url", "urls",
  "user", "users", "uuid",
  "validator", "varchar", "variable", "venv", "vercel",
  "viewport", "vim", "virtual", "vite", "vm", "vpc", "vpn",
  "vue",
  "wasm", "webhook", "webpack", "websocket", "widget", "wiki",
  "wildcard", "worker", "wrapper",
  "xml", "xpath",
  "yaml",
  "zip", "zod",

  // -- Business/marketing jargon --
  "ads", "affiliate", "analytics", "backlog", "banger", "benchmark",
  "board", "bottleneck", "brainstorm", "brand", "brief",
  "buyout",
  "campaign", "canary", "churn", "client", "compliance",
  "conversion", "copywriter", "corporate", "crm",
  "deck", "deliverable", "demo", "discount", "disrupt",
  "ecosystem", "enterprise", "equity",
  "franchise", "freelance", "funnel",
  "giveaway", "gross", "growth",
  "headcount", "headline",
  "incentive", "invoice", "ipo", "iteration",
  "kpi",
  "landing", "leads", "lean",
  "margin", "marketplace", "markup", "merchandise", "merger",
  "monetize",
  "nda", "net", "niche",
  "onboarding", "ops", "outbound", "outsource", "overhead",
  "partnership", "payroll", "persona", "pipeline", "pivot",
  "playbook", "portfolio", "positioning", "premium",
  "procurement", "profit",
  "quota",
  "rebrand", "recurring", "reps", "repurposer", "retail",
  "retainer", "retainers", "retention", "rev", "roadmap", "roi",
  "runway",
  "saas", "scaffold", "scaling", "segment", "seo", "shareholder",
  "sprint", "stakeholder", "strategy", "subscription",
  "synergy",
  "tactic", "target", "tender", "throughput", "tradeoff",
  "traction",
  "upsell", "upside",
  "valuation", "value", "vendor", "venture", "vertical",
  "visibility", "vision",
  "webinar", "workbook", "workflow",
  "yield",

  // -- Calendar / time words --
  "monday", "tuesday", "wednesday", "thursday", "friday", "saturday",
  "sunday", "mon", "tue", "wed", "thu", "fri", "sat", "sun",
  "january", "february", "march", "april", "may", "june", "july",
  "august", "september", "october", "november", "december",
  "jan", "feb", "mar", "apr", "jun", "jul", "aug", "sep",
  "oct", "nov", "dec",
  "today", "yesterday", "tomorrow", "tonight", "morning",
  "afternoon", "evening", "night", "midnight", "noon",
  "hour", "minute", "second", "week", "month", "year",
  "day", "days", "daily", "weekly", "monthly", "nightly", "hourly",
  "annual", "quarterly",

  // -- Place words / geographic --
  "australia", "city", "continent", "country", "county", "district",
  "dublin", "earth", "europe", "ireland", "irish", "island",
  "miami", "north", "south", "east", "west", "ocean", "planet",
  "region", "state", "territory", "town", "village", "world",

  // -- Misc words that appeared as garbage person entities --
  "observability", "obsidian", "pocketdrop", "paperclip", "nova",
  "andromeda", "lightpanda", "gigabrain", "inovativ", "brandloom",
  "hillsong", "claw", "claws", "bizzuka",

  // -- Additional common words / tech-product names that are NOT person names --
  // These are either dictionary words or well-known product/brand names that
  // should not be classified as "person" entities. They may still be valid
  // as project/org entities, but the person-name filter catches them.
  "alt", "analyzed", "append", "approve", "asset",
  "blog", "brief", "builder",
  "captured", "chart", "chat", "clean", "client", "closed", "coaching",
  "codex", "coe", "coming", "competitors", "completed", "complex",
  "complexity", "compliance", "compound", "concept", "configure",
  "confirmation", "confirmed", "constraints", "consulting", "copilot",
  "core", "corporate", "cost", "cowork", "created", "critical",
  "cunningham", "custom",
  "dashboard", "deep", "deliverable", "delivery", "department",
  "deployed", "designer", "dev", "diagnostic", "dialogue", "digital",
  "direct", "disable", "discord", "discovery", "drift",
  "easily", "edit", "embedded", "empty", "enable", "engine",
  "engineering", "engram", "entries", "entry", "environment",
  "episodic", "essay", "essential", "estimate", "europe",
  "examples", "execute", "execution", "executive", "existing",
  "expert", "explicit", "external", "extraction",
  "factory", "failed", "fallback", "fast", "features", "fetch",
  "financial", "fleet", "focus", "format", "founder", "framework",
  "frameworks", "frequency", "fresh",
  "gamma", "gap", "gate", "gathered", "generally", "generate",
  "generating", "generation", "giant", "git", "giveaway",
  "given", "goal", "google", "gradient", "gradual", "grayed",
  "handler", "harness", "hashmeta", "headline", "heartbeat",
  "hey", "holding", "hooks", "hourly", "huge", "human", "hybrid",
  "idle", "implementation", "improvement", "inbox", "incident",
  "individual", "infrastructure", "input", "insight", "install",
  "intake", "integrate", "intelligence", "interface",
  "killer", "kit", "knowledge",
  "lead", "learning", "ledger", "legacy", "legends", "level",
  "leverage", "lifecycle", "linear", "list", "live", "location",
  "locked", "logged", "logging", "long", "looking", "loop",
  "lossless", "low",
  "machine", "main", "maintain", "making", "market", "mart",
  "massive", "maybe", "meeting", "mentor", "meta", "metadata",
  "metrics",
  "mid", "minion", "missing", "mission", "modified",
  "money", "monthly", "morning", "motivational", "multiple",
  "must",
  "napkin", "native", "nearshore", "needed", "never", "next",
  "niche", "nightly", "nobody", "node", "noise", "none",
  "noted", "nudge",
  "objection", "observation", "obviously", "offer", "offers",
  "okay", "one", "openclaw", "operating", "operations", "operator",
  "option", "optional", "order", "orient", "outbound", "outputs",
  "overnight", "owner",
  "package", "page", "paid", "panel", "partnership", "pass",
  "passed", "peak", "pending", "performance", "phone", "pitch",
  "planner", "playbook", "pleasure", "point", "port", "position",
  "positioning", "post", "power", "pre", "prefetch", "premium",
  "prep", "previously", "price", "pricing", "primary", "prior",
  "priority", "probe", "process", "processes", "product",
  "production", "professional", "program", "progress", "projects",
  "promise", "promote", "protection", "protocol", "provider",
  "python",
  "quality", "queue", "quotes",
  "railway", "ran", "rate", "read", "readiness", "ready", "real",
  "recall", "recommendation", "recommended", "reconfirmed",
  "recurrence", "register", "related", "remaining", "reports",
  "reproducible", "reps", "repurposer", "request", "requested",
  "research", "resend", "resolved", "resolving", "respond",
  "response", "responses", "retainers", "retrieval", "rev",
  "revenue", "reviewed", "revised", "rewrite", "risk",
  "rollover", "router", "running",
  "safe", "sales", "save", "scarcity", "schema", "secret",
  "see", "seen", "segment", "sender", "senior", "separate",
  "sequence", "sequential", "service", "services", "settings",
  "seven", "show", "shows", "signal", "simple", "size",
  "skeptics", "skill", "slack", "slackbot", "sleep", "small",
  "snowball", "social", "software", "sometimes", "soon",
  "source", "spawn", "specialist", "specialized", "specific",
  "spend", "split", "sprint", "stack", "stale", "standard",
  "standing", "standup", "start", "started", "starter", "static",
  "still", "strategy", "strength", "stripe", "structure",
  "subagent", "subject", "submit", "substack", "suggested",
  "synthesized",
  "tactics", "tags", "tailscale", "talk", "target", "team",
  "telegram", "template", "terms", "terrible", "text", "they",
  "things", "three", "tier", "tiered", "tightened", "timeline",
  "timer", "title", "total", "training", "transcript", "transient",
  "tree", "trust", "truth", "turn", "twitter", "two", "type",
  "unchanged", "unified", "unknown", "updated", "upfront",
  "usage", "uses",
  "venture", "vercel", "verified", "video", "videos", "visible",
  "vision", "vite", "voice",
  "waiting", "warning", "weather", "webinar", "website", "weekly",
  "welcome", "what", "whether", "why", "wire", "work", "workbook",
  "workflows", "workgraph", "works", "write", "writer",
  "yeah", "you", "zero", "zone",
]);

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns true if the given single-word token (lowercase, trimmed) looks like
 * a common English word rather than a real entity name.
 *
 * For multi-word strings, only the individual tokens are checked.
 */
export function isCommonEnglishWord(token: string): boolean {
  const normalized = token.trim().toLowerCase();
  if (!normalized) return false;
  return COMMON_ENGLISH_WORDS.has(normalized);
}

/**
 * Returns true if the entity name passes quality checks and is likely a real
 * entity (person, org, project) rather than a common English word.
 *
 * Rules:
 * 1. Multi-word names (2+ tokens) are much more likely to be real names,
 *    so they pass with minimal filtering.
 * 2. Single-word names must NOT be common English words.
 * 3. Single-word names that are very short (< 3 chars) are rejected.
 * 4. Single-word names that are all-lowercase and match dictionary are rejected.
 */
export function isLikelyEntityName(name: string): boolean {
  const normalized = name.trim().toLowerCase();
  if (!normalized) return false;

  const tokens = normalized.split(/\s+/).filter(Boolean);

  // Multi-word names: check that at least one token is not a common word
  if (tokens.length >= 2) {
    return tokens.some((t) => !isCommonEnglishWord(t));
  }

  // Single token
  const token = tokens[0];
  if (!token || token.length < 3) return false;

  // Pure numeric or mostly numeric
  if (/^\d+$/.test(token)) return false;

  // Common English word filter — the core fix
  if (COMMON_ENGLISH_WORDS.has(token)) return false;

  return true;
}

/**
 * Confidence floor for person entities. Entity candidates below this
 * confidence should not be admitted regardless of other signals.
 */
export const PERSON_MIN_CONFIDENCE = 0.60;

/**
 * Confidence floor for organization entities.
 */
export const ORG_MIN_CONFIDENCE = 0.55;

/**
 * Confidence floor for project entities.
 */
export const PROJECT_MIN_CONFIDENCE = 0.55;
